# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5761ccce3345628974620d8f2b1bd4ac0630a3ecde0bb1e72068b62d7b9c168945902b075fee1e316c9bd0e5b8989ebd492563bf19e4e26fcdb8aa264ebe86

test:
  secret_key_base: 5cb017cf50e730e22f80469718e558f487fe1c376f83f758eec6aa27a2a765357ece3a4e655845c6cf8adb4aaf07ca6d02849b96b42e2492d9f719cf438b8eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
